config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :conferences do

    resources :registrants do
      resources :organizations
      resources :invoices

    end

    resources :sessions
    resources :proposals
  end

  resources :sessions
  resources :registrants
  resources :organizations
  resources :invoices

  get '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  post '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  get '/home', :controller => 'start', :action => 'home'
  get '/planner', :controller => 'start', :action => 'plan'

  get '/auth/:provider/callback', :controller => 'googlesync', :action => 'init_api'
  get '/drivesync', :controller => 'googlesync', :action => 'init_api'
  root to: 'start#index'

end

app/models/registrant.rb
class Registrant < ActiveRecord::Base
  belongs_to :conference
  searchable do
   text :firstname
   text :lastname
  end
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  before_action :set_registrant, only: [:show, :edit, :update, :destroy]

  # GET /registrants
  # GET /registrants.json
  def index
    # Only find the registrants for the particular conference
    @registrants = Registrant.where(conference_id: params[:conference_id]).all
  end

  # GET /registrants/1
  # GET /registrants/1.json
  def show
  end

  # GET /registrants/new
  def new
    @registrant = Registrant.new
  end

  # GET /registrants/1/edit
  def edit
  end

  # POST /registrants
  # POST /registrants.json
  def create
    @registrant = Registrant.new(registrant_params)

    respond_to do |format|
      if @registrant.save
        format.html { redirect_to @registrant, notice: 'Registrant was successfully created.' }
        format.json { render :show, status: :created, location: @registrant }
      else
        format.html { render :new }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrants/1
  # PATCH/PUT /registrants/1.json
  def update
    respond_to do |format|
      if @registrant.update(registrant_params)
        format.html { redirect_to @registrant, notice: 'Registrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @registrant }
      else
        format.html { render :edit }
        format.json { render json: @registrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrants/1
  # DELETE /registrants/1.json
  def destroy
    @registrant.destroy
    respond_to do |format|
      format.html { redirect_to(:controller => :registrants, :action => :index, conference_id: params[:conference_id], notice: 'Registrant was successfully unregistered.') }
      format.json { head :no_content }
    end
  end

  # GET /registrants/actions/search?q=
  def search
    @registants = Registrants.search { fulltext params[:q] }
    respond_to do |format|
      format.html "search_results"
      format.json { render json: @registrants }
    end
  end

  # GET /registrants/actions/badges
  def badges
    # Generate SQL
    # first, make sure the id params can be safely converted to ints
    @ids = params[:badge].keys.select{ |id| id.to_i != 0 } if params[:badge] != nil
    #@ids = @ids.map{ |id| id.to_i }
    #@idwhereparams = "(" + ids.map{ |id| "id = #{id.to_i}" }.join(" OR ") + ")"
    #@sql = "SELECT * FROM registrants where conference_id = ? AND " + @idwhereparams
    if @ids != nil && @ids.length > 0
      @registrants = Registrant.where(conference_id: params[:conference_id], id: @ids).all
    else
      @registrants = Registrant.where(conference_id: params[:conference_id])
    end
    respond_to do |format|
      format.html { render "badges" }
      format.pdf do
        pdf = Badge.new(@registrants)
        send_data pdf.render, filename: 'badges.pdf', type: 'application/pdf', disposition: 'inline; filename="badges.pdf"'
      end
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_registrant
      @registrant = Registrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registrant_params
      params.require(:registrant).permit(:firstname, :lastname, :middleinitial, :homenumber, :homestreet, :homecity, :homestate, :homezip, :homephone, :cellphone, :businessname, :businessnumber, :businessstreet, :businesscity, :businessstate, :businesszip, :conference_id, :print_badge)
    end

end

app/helpers/registrants_helper.rb
module RegistrantsHelper
end

app/views/registrants/_form.html.erb
<%= form_for(@registrant) do |f| %>
  <% if @registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registrant.errors.count, "error") %> prohibited this registrant from being saved:</h2>

      <ul>
      <% @registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <p>Conference: <%= Conference.find(params[:conference_id]).name %></p>
    <%= f.hidden_field :conference_id, value: params[:conference_id] , readonly: true %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :middleinitial %><br>
    <%= f.text_field :middleinitial %>
  </div>
  <div class="field">
    <%= f.label :homenumber %><br>
    <%= f.number_field :homenumber %>
  </div>
  <div class="field">
    <%= f.label :homestreet %><br>
    <%= f.text_field :homestreet %>
  </div>
  <div class="field">
    <%= f.label :homecity %><br>
    <%= f.text_field :homecity %>
  </div>
  <div class="field">
    <%= f.label :homestate %><br>
    <%= f.text_field :homestate %>
  </div>
  <div class="field">
    <%= f.label :homezip %><br>
    <%= f.number_field :homezip %>
  </div>
  <div class="field">
    <%= f.label :homephone %><br>
    <%= f.number_field :homephone %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br>
    <%= f.number_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :businessname %><br>
    <%= f.text_field :businessname %>
  </div>
  <div class="field">
    <%= f.label :businessnumber %><br>
    <%= f.number_field :businessnumber %>
  </div>
  <div class="field">
    <%= f.label :businessstreet %><br>
    <%= f.text_field :businessstreet %>
  </div>
  <div class="field">
    <%= f.label :businesscity %><br>
    <%= f.text_field :businesscity %>
  </div>
  <div class="field">
    <%= f.label :businessstate %><br>
    <%= f.text_field :businessstate %>
  </div>
  <div class="field">
    <%= f.label :businesszip %><br>
    <%= f.number_field :businesszip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registrants/badges.html.erb
<p id="notice"><%= notice %></p>
<h1>Badge Printing</h1>
<h2>Please select the Individuals whose badge you want to print. To Print all, just hit Print Badges</h2>
<h3>You can also print badges at any time by clicking Print Selected Badges next to any registration entry</h3>
<form method="POST" action="/conferences/<%= params[:conference_id] %>/registrants/actions/badges.pdf">
  <!-- add the rails token, for external apis,
      check http://stackoverflow.com/questions/16258911/rails-4-authenticity-token for solution -->
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
  <input type="submit" value="Print Selected Badges" />
  <% @registrants.each do |registrant| %>
    <div class="registrant">
    <%= registrant.firstname %>
    <%= registrant.lastname %>
      <input name="badge[<%= registrant.id %>]" value="<%= registrant.id %>" type="checkbox" /><input type="submit" value="Print Selected Badges" />
    </div>
  <% end %>
  <input type="submit" value="Print Selected Badges" />
  <script type="text/javascript">
    // don't do this, we don't need it.
    // var TheCenter = (typeof TheCenter != "undefined") ? TheCenter : new Object();
    // TheCenter.PrintBadges = function() {
    //   // ^= -> startswith, see http://www.w3.org/TR/css3-selectors/
    //   var selectedBadges = document.querySelectorAll("[name^='badge']:checked");
    //   console.log(selectedBadges.length);
    //   var sids = [];
    //   for (var i = 0; i < selectedBadges.length; i++) {
    //     sids.push(selectedBadges[i].value);
    //   }
    //   console.log(sids.length);
    //   console.log(sids);
    //   sids = JSON.stringify(sids);
    //   var responseBadges = "";
    //   // submit the data
    //   var xhr = new XMLHttpRequest();
    //   xhr.open('POST', '/conferences/<%= params[:conference_id] %>/registrants/actions/badges.pdf', true);
    //   xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
    //   xhr.setRequestHeader('<%= request_forgery_protection_token.to_s %>', '<%= form_authenticity_token %>');
    //   xhr.send(sids);
    //
    //   switch (xhr.status) {
    //     case 200:
    //       responseBadges = xhr.responseXML;
    //       document.body.appendChild(responseBadges);
    //       break;
    //     default:
    //       console.log("Response Bad");
    //   }
    // };
  </script>
</form>

app/views/registrants/edit.html.erb
<h1>Editing Registrant</h1>

<%= render 'form' %>

<%= link_to 'Show', @registrant %> |
<%= link_to 'Back', conferences_path %>

app/views/registrants/index.html.erb
<!-- allow for both notice and params[:notice] until I figure out how to redirect
  the DELETE method correctly -->
<p id="notice"><%= notice %><%= params[:notice] if params[:notice] %></p>


<h1>Registrations</h1>
<h2><%= Conference.find(params[:conference_id]).name %></h2>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Middleinitial</th>
      <th>Homenumber</th>
      <th>Homestreet</th>
      <th>Homecity</th>
      <th>Homestate</th>
      <!--th>Homezip</th>
      <th>Homephone</th>
      <th>Cellphone</th>
      <th>Businessname</th>
      <th>Businessnumber</th>
      <th>Businessstreet</th>
      <th>Businesscity</th>
      <th>Businessstate</th>
      <th>Businesszip</th-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registrants.each do |registrant| %>
      <tr>
        <td><%= registrant.firstname %></td>
        <td><%= registrant.lastname %></td>
        <td><%= registrant.middleinitial %></td>
        <td><%= registrant.homenumber %></td>
        <td><%= registrant.homestreet %></td>
        <td><%= registrant.homecity %></td>
        <td><%= registrant.homestate %></td>
        <!--td><%= registrant.homezip %></td>
        <td><%= registrant.homephone %></td>
        <td><%= registrant.cellphone %></td>
        <td><%= registrant.businessname %></td>
        <td><%= registrant.businessnumber %></td>
        <td><%= registrant.businessstreet %></td>
        <td><%= registrant.businesscity %></td>
        <td><%= registrant.businessstate %></td>
        <td><%= registrant.businesszip %></td-->
        <td><%= link_to 'Show', registrant_path(registrant, conference_id: params[:conference_id]) %></td>
        <td><%= link_to 'Edit', edit_registrant_path(registrant, conference_id: params[:conference_id]) %></td>
        <td><%= link_to 'Destroy', registrant_path(registrant, conference_id: params[:conference_id], method: :delete, data: { confirm: 'Are you sure?' }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registrant', new_conference_registrant_path %>
<%= link_to 'Print Badges', "registrants/actions/badges" %>

app/views/registrants/new.html.erb
<h1>New Registrant</h1>

<%= render 'form' %>

<%= link_to 'Back', registrants_path %>

app/views/registrants/search_results.html.erb
<% @registrants.each do |registrant| %>
<p><% registrant.id %></p>
<p><% registrant.firstname %></p>
<p><% registrant.lastname %></p>
<% link_to 'Show', registrant %>

app/views/registrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @registrant.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @registrant.lastname %>
</p>

<p>
  <strong>Middleinitial:</strong>
  <%= @registrant.middleinitial %>
</p>

<p>
  <strong>Homenumber:</strong>
  <%= @registrant.homenumber %>
</p>

<p>
  <strong>Homestreet:</strong>
  <%= @registrant.homestreet %>
</p>

<p>
  <strong>Homecity:</strong>
  <%= @registrant.homecity %>
</p>

<p>
  <strong>Homestate:</strong>
  <%= @registrant.homestate %>
</p>

<p>
  <strong>Homezip:</strong>
  <%= @registrant.homezip %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @registrant.homephone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @registrant.cellphone %>
</p>

<p>
  <strong>Businessname:</strong>
  <%= @registrant.businessname %>
</p>

<p>
  <strong>Businessnumber:</strong>
  <%= @registrant.businessnumber %>
</p>

<p>
  <strong>Businessstreet:</strong>
  <%= @registrant.businessstreet %>
</p>

<p>
  <strong>Businesscity:</strong>
  <%= @registrant.businesscity %>
</p>

<p>
  <strong>Businessstate:</strong>
  <%= @registrant.businessstate %>
</p>

<p>
  <strong>Businesszip:</strong>
  <%= @registrant.businesszip %>
</p>

<%= link_to 'Edit', edit_registrant_path(@registrant, conference_id: @registrant.conference_id) %> |
<%= link_to 'Back', conference_registrants_path(@registrant.conference_id) %>