config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :conferences do

    resources :registrants do
      resources :organizations
      resources :invoices

    end

    resources :sessions
    resources :proposals
  end

  resources :sessions
  resources :registrants
  resources :organizations
  resources :invoices

  get '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  post '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  get '/home', :controller => 'start', :action => 'home'
  get '/planner', :controller => 'start', :action => 'plan'

  get '/auth/:provider/callback', :controller => 'googlesync', :action => 'init_api'
  get '/drivesync', :controller => 'googlesync', :action => 'init_api'
  root to: 'start#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :registrants, dependent: :destroy
  has_many :sessions, dependent: :destroy
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferencese
  # GET /conferences.json
  def index
    @conferences = Conference.all
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :date, :fiscal_year, :locationname, :locationstreet, :locationnumber, :locationcity, :locationzip)
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 75 %>
  </div>
  <div class="field">
    <%= f.label :fiscal_year %>
    <%= f.date_select :fiscal_year, discard_day: true, discard_month: true, start_year: Date.today.year - 10, end_year: Date.today.year + 20 %>
  </div>
  <div class="field">
    <%= f.label :date %> <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :locationname, "Location" %><br>
    <%= f.text_field :locationname %>
  </div>
  <div class="field address">
    <%= f.label :locationnumber, "Number" %><br>
    <%= f.number_field :locationnumber %>
  </div>
  <div class="field address">
    <%= f.label :locationstreet, "Street" %><br>
    <%= f.text_field :locationstreet %>
  </div>
  <div class="field address">
    <%= f.label :locationcity, "City" %><br>
    <%= f.text_field :locationcity %>
  </div>
  <div class="field address">
    <%= f.label :locationzip, "Zip Code" %><br>
    <%= f.number_field :locationzip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing Conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Locationname</th>
      <th>Locationstreet</th>
      <th>Locationnumber</th>
      <th>Locationcity</th>
      <th>Locationzip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.name %></td>
        <td><%= conference.date %></td>
        <td><%= conference.locationname %></td>
        <td><%= conference.locationstreet %></td>
        <td><%= conference.locationnumber %></td>
        <td><%= conference.locationcity %></td>
        <td><%= conference.locationzip %></td>
        <td><%= link_to 'Info', conference %></td>
        <td><%= link_to 'Edit Info', edit_conference_path(conference) %></td>
        <td><%= link_to 'Registrations', conference_registrants_path(conference) %></td>
        <td><%= link_to 'Add Registrations', new_conference_registrant_path(conference) %></td>
        <td><%= link_to 'Print Badges', "/conferences/" + conference.id.to_s + "/registrants/actions/badges" %></td>
        <td><%= link_to 'Schedule Sessions', conference_sessions_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New Conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference.name %>
</p>

<p>
  <strong>Date:</strong>
  <%# pretty print the date #%>
  <%= Date::MONTHNAMES[@conference.date.month] %> <%= @conference.date.day %>, <%= @conference.date.year %>
</p>

<p>
  <strong>Location:</strong>
  <div><%= @conference.locationname %>
       <div><%= @conference.locationnumber %>, <%= @conference.locationstreet %></div>
       <div><%= @conference.locationcity %> IL, <%= @conference.locationzip %></div>
  </div>
</p>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>