config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :conferences do

    resources :registrants do
      resources :organizations
      resources :invoices

    end

    resources :sessions
    resources :proposals
  end

  resources :sessions
  resources :registrants
  resources :organizations
  resources :invoices

  get '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  post '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  get '/home', :controller => 'start', :action => 'home'
  get '/planner', :controller => 'start', :action => 'plan'

  get '/auth/:provider/callback', :controller => 'googlesync', :action => 'init_api'
  get '/drivesync', :controller => 'googlesync', :action => 'init_api'
  root to: 'start#index'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :session
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  before_action :set_proposal, only: [:show, :edit, :update, :destroy]


  def sync!
    mappings_path = File.join(File.dirname(__FILE__), '..', '..', 'config', 'sheets-mapping.yml')
    DriveTime::OauthSpreadsheetsConverter.new.load mappings_path
  end



  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:firstname, :lastname, :title, :abstract)
    end
end

app/helpers/proposals_helper.rb
# Proposals helper is just an extension of drive_time to make it work with oauth
# So as to not violate MVC, OauthSpreadsheetsConverter must be passed an
# access_token from the Token model.
# This should be converted to middleware or model, but shouldn't be here
module ProposalsHelper end

module DriveTime

  class OauthLoader < Loader

    # @params access_token: authenticated google api access token
    def begin_session(access_token=nil)
      access_token ||= Token.last.fresh_token
      # load the token
      @session = GoogleDrive.login_with_oauth(access_token)
    end

  end


  class OauthSpreadsheetsConverter < SpreadsheetsConverter

    def initialize
      # convert the spreadsheet with our new oauth loader. do everything the overridden method does
      # otherwise (why doesn't super work if I just want to change an instance variable?)
      @dependency_graph = DeepEnd::Graph.new
      @loader = OauthLoader.new
      @model_store = ModelStore.new(DriveTime::log_level)
      @class_name_map = ClassNameMap.new
    end

  end

end

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this session from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Session Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label "Abstract" %><br>
    <%= f.text_field :abstract %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<p id="notice"><%= notice %></p>


<h1><%= Conference.find(params[:conference_id]).name %></h1>
<h2>Conference Planner</h2>


<table>
  <thead>
    <tr>
      <th>Presenterid</th>
      <th>Copresenter</th>
      <th>Conferenceid</th>
      <th>Title</th>
      <th>Description</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Strand</th>
      <th>Roomid</th>
      <th>Level</th>
      <th>Setuporderid</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sessions.each do |session| %>
      <tr>
        <td><%= session.presenterid %></td>
        <td><%= session.copresenter_id %></td>
        <td><%= session.conferenceid %></td>
        <td><%= session.title %></td>
        <td><%= session.description %></td>
        <td><%= session.starttime %></td>
        <td><%= session.endtime %></td>
        <td><%= session.strand %></td>
        <td><%= session.roomid %></td>
        <td><%= session.level %></td>
        <td><%= session.setuporderid %></td>
        <td><%= session.language %></td>
        <td><%= link_to 'Show', session %></td>
        <td><%= link_to 'Edit', edit_session_path(session) %></td>
        <td><%= link_to 'Destroy', session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Session', new_session_path %>

app/views/proposals/new.html.erb
<h1>New Session</h1>

<%= render 'form' %>

<%= link_to 'Back', sessions_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proposal:</strong>
  <%= @proposal.title %>
</p>

<p>
  <strong>Presenter</strong>
  <%= @proposal.firstname %> <%= @proposal.lastname %>
</p>

<p>
  <strong>Abstract</strong>
  <%= @proposal.abstract %>
</p>



<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposal_path %>