config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :conferences do

    resources :registrants do
      resources :organizations
      resources :invoices

    end

    resources :sessions
    resources :proposals
  end

  resources :sessions
  resources :registrants
  resources :organizations
  resources :invoices

  get '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  post '/conferences/:conference_id/registrants/actions/badges', :controller => 'registrants', :action => 'badges'
  get '/home', :controller => 'start', :action => 'home'
  get '/planner', :controller => 'start', :action => 'plan'

  get '/auth/:provider/callback', :controller => 'googlesync', :action => 'init_api'
  get '/drivesync', :controller => 'googlesync', :action => 'init_api'
  root to: 'start#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:buildingname, :address, :city, :zip, :telephone, :kind, :department_fields)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buildingname %><br>
    <%= f.text_field :buildingname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.number_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.hidden_field :department_fields %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Buildingname</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th>Telephone</th>
      <th>Kind</th>
      <th>Department fields</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.buildingname %></td>
        <td><%= organization.address %></td>
        <td><%= organization.city %></td>
        <td><%= organization.zip %></td>
        <td><%= organization.telephone %></td>
        <td><%= organization.kind %></td>
        <td><%= organization.department_fields %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Buildingname:</strong>
  <%= @organization.buildingname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organization.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @organization.zip %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @organization.telephone %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @organization.kind %>
</p>

<p>
  <strong>Department fields:</strong>
  <%= @organization.department_fields %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>